#! /bin/bash
# Installs all the tools for a new Linux - computer, server or desktop. Must be Debian - based. 
# Written by Andreas Mosti, based on script from eg1l 
# Warning: The zsh - configs works badly in OS X... 
# V1.2: Added OS - detection to avoid errors while running   
# V1.2.1: Bugfix 
# V1.3: Added zsh - configurator from TJuberg, bad fit with OS X  
# V1.4: Added gem - installer.
# V1.5: Added some git-stuff and began cleanup of file.

if [[ "$(uname)" != "Linux" ]]
then 
	echo "Wrong OS!!"
	sleep 1
	exit
fi 

echo -n "Is this a new server?(y/n)"
read  svar 

if [[ $svar == "y" ]]
then
 	programs="build-essential vim tor nmap ssh curl irssi fail2ban apg smbclient htop git hydra zsh make traceroute mosh screen
    smbfs mailutils python-dev ufw oidentd ruby"
	
	echo "Server install"
	sleep 2
    
    echo "Do you need DNS on the server? (Bind)(y/n)"
    read dns 
if [[ $dns == "y" ]] 
then 
    install bind9
else 
    echo "No DNS." 
    sleep 2
fi

else
	programs="build-essential vim tor nmap ssh curl irssi fail2ban apg smbclient htop git zsh transmission gedit texlive gedit-latex-plugin
    thunderbird vlc hydra p7zip-full texmaker make  unetbootin traceroute mosh awesome screen guake sshguard python-dev ufw oidentd terminator ruby"
	
	echo "Desktop install"
	sleep 2 

fi

rubyPrograms="bropages"

function updateSystem() {
sudo apt-get update 
sudo apt-get upgrade -y

    }

function install() {
sudo apt-get install -y $1 >/dev/null 2>&1
	
	}
	
function gemInstall() {
sudo gem install $1 >/dev/null 2>&1

    }

echo "Installing programs.."
sleep 2

updateSystem

for program in $programs
do
	echo "Current package: $program"
    install $programs
done

for gem in $rubyPrograms
do
    echo "Current gem: $gem"
    gemInstall $gem
done

echo "Setting git-options..."
git config --global color.ui true
git config --global core.editor "vim"

echo "Install Complete."
sleep 2

echo "Do you want zsh and vim - config?(y/n)"
read input 

if [[ $input == "y" ]] 
then
    cd; git clone git://github.com/TJuberg/dotfiles.git; ln -s dotfiles/dot.zshrc .zshrc; cp Dropbox/Scripts/.vimrc .; #Dirty fix
    echo "zsh and vim configurated!"
    sleep 2

else 
    echo "No zsh configured."
    sleep 2

fi

echo "Done!"
