#! /bin/bash

if [ -f /usr/bin/makepasswd ]
then 
for i in {1..10}; do makepasswd --minchars 8  --maxchars 24 
done
elif [ -f /opt/local/bin/makepasswd ] 
then  
  for i in {1..10}; do makepasswd --minchars 8  --maxchars 24
  done
else
    echo "makepasswd is not installed."
fi
