#! /bin/bash
# $1 = url
# $2 = description
# $3 = tags, separate with ','

username=""
password=""

curl "https://$username:$password@api.del.icio.us/v1/posts/add?&url=$1&description=$2&tags=$3&replace=no"
