#!/bin/bash

# Skripter symlinker bash_profile - filene mellom maskiner 
# Andreas Mosti 
# Known error: on Linux systems, .bash_profile must be added to bashrc file 
# Version 1.2 : Fixed error if .bash_profile didnt exist. 
# Version 1.3 : Fixed bashrc - sync for Linux systems Possible bug with symlinc if file exists   
 
cd ~ 

if  [[ $(uname) == "Linux" ]] && [[ -f .bashrc ]] 
then 
    rm .bashrc; ln -s ~/Dropbox/Scripts/Profil/.bashrc .bashrc

elif [[ $(uname) == "Linux" ]]; then
    touch .bashrc; ln -s ~/Dropbox/Scripts/Profil/.bashrc .bashrc

fi


if [ -f .bash_profile ]
then 
	rm .bash_profile; ln -s ~/Dropbox/Scripts/Profil/.bash_profile .bash_profile
	echo "Done."
else 
	touch .bash_profile; rm .bash_profile; ln -s ~/Dropbox/Scripts/Profil/.bash_profile .bash_profile

fi


