#! /usr/bin/python

# Basic system info for posix-systems.
# Andreas Mosti, 29.03.2014

import subprocess
import platform

class SysInfo():
    """docstring for SysInfo"""     
    def __init__(self):
        self.hr_line()
        print '\n Basic system information \n'
        self.basic_info()
        self.hr_line()
        print '\n Free memory: \n'
        self.mem_space()
        self.hr_line()
        print '\n Disk info: \n'
        self.disk_space()
        print ''
    
    def disk_space(self):
        subprocess.call('df -h', shell=True)

    def mem_space(self):
        if "Darwin" in platform.platform():
            subprocess.call('~/Dropbox/Scripts/free-memory', shell=True)
        else:
            subprocess.call('free -h', shell=True)

    def basic_info(self):
        if "Darwin" in platform.platform():  
            subprocess.call('sw_vers', shell=True)
        else:
             subprocess.call('cat /etc/issue', shell=True)
        subprocess.call('uname -a', shell=True)
    
    def hr_line(self):
        subprocess.call('~/Dropbox/Scripts/hr', shell=True)

si = SysInfo() 
